
PRINT N'CREATE TABLE [SCHEMA_NAME].[TABLE_NAME]'
GO -- SQRIBE/GO

-- SQRIBE/OBJ
CREATE TABLE [SCHEMA_NAME].[TABLE_NAME]
(
    [COLUMN_NAME] [DATA_TYPE](max) COLLATE SQL_Latin1_General_CP1_CI_AS IDENTITY(1,1) NULL,

) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY] -- SQRIBE/END
GO -- SQRIBE/GO
