SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;341e11

-- SQRIBE/TABLE;341e11
-- Adding 3 rows to Person.PhoneNumberType

SET IDENTITY_INSERT [Person].[PhoneNumberType] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;341e11
INSERT INTO [Person].[PhoneNumberType] ([PhoneNumberTypeID],[Name],[ModifiedDate]) VALUES (1,N'Cell','2017-12-13 13:19:22.273');
-- SQRIBE/INSERT;341e11
INSERT INTO [Person].[PhoneNumberType] ([PhoneNumberTypeID],[Name],[ModifiedDate]) VALUES (2,N'Home','2017-12-13 13:19:22.273');
-- SQRIBE/INSERT;341e11
INSERT INTO [Person].[PhoneNumberType] ([PhoneNumberTypeID],[Name],[ModifiedDate]) VALUES (3,N'Work','2017-12-13 13:19:22.273');

COMMIT TRANSACTION

SET IDENTITY_INSERT [Person].[PhoneNumberType] OFF

