SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;341e11

-- SQRIBE/TABLE;341e11
-- Adding 1 row to dbo.AWBuildVersion

SET IDENTITY_INSERT [dbo].[AWBuildVersion] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;341e11
INSERT INTO [dbo].[AWBuildVersion] ([SystemInformationID],[Database Version],[VersionDate],[ModifiedDate]) VALUES ('1',N'14.0.1000.169','2017-08-22 19:39:35.643','2017-10-27 14:33:02.347');

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[AWBuildVersion] OFF

