SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;341e11
PRINT N'CREATE fulltext catalogs'
GO -- SQRIBE/GO;341e11
-- SQRIBE/OBJ;341e11
CREATE FULLTEXT CATALOG [AW2016FullTextCatalog]
WITH ACCENT_SENSITIVITY = ON
GO -- SQRIBE/GO;341e11

CREATE FULLTEXT INDEX ON [HumanResources].[JobCandidate] (
[Resume] Language 1033 
) 
KEY INDEX [PK_JobCandidate_JobCandidateID]
ON [AW2016FullTextCatalog]
WITH CHANGE_TRACKING AUTO
GO -- SQRIBE/GO;341e11

CREATE FULLTEXT INDEX ON [Production].[Document] (
[DocumentSummary] Language 1033 
,[Document] TYPE COLUMN [FileExtension]
) 
KEY INDEX [PK_Document_DocumentNode]
ON [AW2016FullTextCatalog]
WITH CHANGE_TRACKING AUTO
GO -- SQRIBE/GO;341e11

CREATE FULLTEXT INDEX ON [Production].[ProductReview] (
[Comments] Language 1033 
) 
KEY INDEX [PK_ProductReview_ProductReviewID]
ON [AW2016FullTextCatalog]
WITH CHANGE_TRACKING AUTO
GO -- SQRIBE/GO;341e11

