SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;341e11
PRINT N'CREATE schemas'
GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
IF (NOT EXISTS (SELECT *
    FROM sys.schemas
    WHERE name = 'HumanResources'))
BEGIN
    EXEC ('CREATE SCHEMA [HumanResources] AUTHORIZATION [dbo]')
END
GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
IF (NOT EXISTS (SELECT *
    FROM sys.schemas
    WHERE name = 'Person'))
BEGIN
    EXEC ('CREATE SCHEMA [Person] AUTHORIZATION [dbo]')
END
GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
IF (NOT EXISTS (SELECT *
    FROM sys.schemas
    WHERE name = 'Production'))
BEGIN
    EXEC ('CREATE SCHEMA [Production] AUTHORIZATION [dbo]')
END
GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
IF (NOT EXISTS (SELECT *
    FROM sys.schemas
    WHERE name = 'Purchasing'))
BEGIN
    EXEC ('CREATE SCHEMA [Purchasing] AUTHORIZATION [dbo]')
END
GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
IF (NOT EXISTS (SELECT *
    FROM sys.schemas
    WHERE name = 'Sales'))
BEGIN
    EXEC ('CREATE SCHEMA [Sales] AUTHORIZATION [dbo]')
END
GO -- SQRIBE/GO;341e11
