SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;341e11
PRINT N'CREATE indices'
GO -- SQRIBE/GO;341e11
-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Department_Name] ON [HumanResources].[Department] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Employee_LoginID] ON [HumanResources].[Employee] ([LoginID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Employee_NationalIDNumber] ON [HumanResources].[Employee] ([NationalIDNumber] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Employee_rowguid] ON [HumanResources].[Employee] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_Employee_OrganizationLevel_OrganizationNode] ON [HumanResources].[Employee] ([OrganizationLevel] ASC, [OrganizationNode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_Employee_OrganizationNode] ON [HumanResources].[Employee] ([OrganizationNode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_EmployeeDepartmentHistory_DepartmentID] ON [HumanResources].[EmployeeDepartmentHistory] ([DepartmentID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_EmployeeDepartmentHistory_ShiftID] ON [HumanResources].[EmployeeDepartmentHistory] ([ShiftID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_JobCandidate_BusinessEntityID] ON [HumanResources].[JobCandidate] ([BusinessEntityID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Shift_Name] ON [HumanResources].[Shift] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Shift_StartTime_EndTime] ON [HumanResources].[Shift] ([StartTime] ASC, [EndTime] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Address_rowguid] ON [Person].[Address] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [IX_Address_AddressLine1_AddressLine2_City_StateProvinceID_PostalCode] ON [Person].[Address] ([AddressLine1] ASC, [AddressLine2] ASC, [City] ASC, [StateProvinceID] ASC, [PostalCode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_Address_StateProvinceID] ON [Person].[Address] ([StateProvinceID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_AddressType_Name] ON [Person].[AddressType] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_AddressType_rowguid] ON [Person].[AddressType] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_BusinessEntity_rowguid] ON [Person].[BusinessEntity] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_BusinessEntityAddress_rowguid] ON [Person].[BusinessEntityAddress] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_BusinessEntityAddress_AddressID] ON [Person].[BusinessEntityAddress] ([AddressID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_BusinessEntityAddress_AddressTypeID] ON [Person].[BusinessEntityAddress] ([AddressTypeID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_BusinessEntityContact_rowguid] ON [Person].[BusinessEntityContact] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_BusinessEntityContact_ContactTypeID] ON [Person].[BusinessEntityContact] ([ContactTypeID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_BusinessEntityContact_PersonID] ON [Person].[BusinessEntityContact] ([PersonID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ContactType_Name] ON [Person].[ContactType] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_CountryRegion_Name] ON [Person].[CountryRegion] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_EmailAddress_EmailAddress] ON [Person].[EmailAddress] ([EmailAddress] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Person_rowguid] ON [Person].[Person] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_Person_LastName_FirstName_MiddleName] ON [Person].[Person] ([LastName] ASC, [FirstName] ASC, [MiddleName] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE PRIMARY XML INDEX [PXML_Person_AddContact] ON [Person].[Person] ([AdditionalContactInfo]) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE PRIMARY XML INDEX [PXML_Person_Demographics] ON [Person].[Person] ([Demographics]) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE XML INDEX [XMLPATH_Person_Demographics] ON [Person].[Person] ([Demographics]) USING XML INDEX [PXML_Person_Demographics] FOR PATH WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE XML INDEX [XMLPROPERTY_Person_Demographics] ON [Person].[Person] ([Demographics]) USING XML INDEX [PXML_Person_Demographics] FOR PROPERTY WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE XML INDEX [XMLVALUE_Person_Demographics] ON [Person].[Person] ([Demographics]) USING XML INDEX [PXML_Person_Demographics] FOR VALUE WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_PersonPhone_PhoneNumber] ON [Person].[PersonPhone] ([PhoneNumber] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_StateProvince_Name] ON [Person].[StateProvince] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_StateProvince_rowguid] ON [Person].[StateProvince] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_StateProvince_StateProvinceCode_CountryRegionCode] ON [Person].[StateProvince] ([StateProvinceCode] ASC, [CountryRegionCode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE CLUSTERED INDEX [AK_BillOfMaterials_ProductAssemblyID_ComponentID_StartDate] ON [Production].[BillOfMaterials] ([ProductAssemblyID] ASC, [ComponentID] ASC, [StartDate] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_BillOfMaterials_UnitMeasureCode] ON [Production].[BillOfMaterials] ([UnitMeasureCode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Culture_Name] ON [Production].[Culture] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Document_DocumentLevel_DocumentNode] ON [Production].[Document] ([DocumentLevel] ASC, [DocumentNode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Document_rowguid] ON [Production].[Document] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_Document_FileName_Revision] ON [Production].[Document] ([FileName] ASC, [Revision] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Location_Name] ON [Production].[Location] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Product_Name] ON [Production].[Product] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Product_ProductNumber] ON [Production].[Product] ([ProductNumber] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Product_rowguid] ON [Production].[Product] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ProductCategory_Name] ON [Production].[ProductCategory] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ProductCategory_rowguid] ON [Production].[ProductCategory] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ProductDescription_rowguid] ON [Production].[ProductDescription] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ProductModel_Name] ON [Production].[ProductModel] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ProductModel_rowguid] ON [Production].[ProductModel] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE PRIMARY XML INDEX [PXML_ProductModel_CatalogDescription] ON [Production].[ProductModel] ([CatalogDescription]) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE PRIMARY XML INDEX [PXML_ProductModel_Instructions] ON [Production].[ProductModel] ([Instructions]) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_ProductReview_ProductID_Name] ON [Production].[ProductReview] ([ProductID] ASC, [ReviewerName] ASC) INCLUDE ([Comments])WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ProductSubcategory_Name] ON [Production].[ProductSubcategory] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ProductSubcategory_rowguid] ON [Production].[ProductSubcategory] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ScrapReason_Name] ON [Production].[ScrapReason] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_TransactionHistory_ProductID] ON [Production].[TransactionHistory] ([ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_TransactionHistory_ReferenceOrderID_ReferenceOrderLineID] ON [Production].[TransactionHistory] ([ReferenceOrderID] ASC, [ReferenceOrderLineID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_TransactionHistoryArchive_ProductID] ON [Production].[TransactionHistoryArchive] ([ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_TransactionHistoryArchive_ReferenceOrderID_ReferenceOrderLineID] ON [Production].[TransactionHistoryArchive] ([ReferenceOrderID] ASC, [ReferenceOrderLineID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_UnitMeasure_Name] ON [Production].[UnitMeasure] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_WorkOrder_ProductID] ON [Production].[WorkOrder] ([ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_WorkOrder_ScrapReasonID] ON [Production].[WorkOrder] ([ScrapReasonID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_WorkOrderRouting_ProductID] ON [Production].[WorkOrderRouting] ([ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_ProductVendor_BusinessEntityID] ON [Purchasing].[ProductVendor] ([BusinessEntityID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_ProductVendor_UnitMeasureCode] ON [Purchasing].[ProductVendor] ([UnitMeasureCode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_PurchaseOrderDetail_ProductID] ON [Purchasing].[PurchaseOrderDetail] ([ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_PurchaseOrderHeader_EmployeeID] ON [Purchasing].[PurchaseOrderHeader] ([EmployeeID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_PurchaseOrderHeader_VendorID] ON [Purchasing].[PurchaseOrderHeader] ([VendorID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ShipMethod_Name] ON [Purchasing].[ShipMethod] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_ShipMethod_rowguid] ON [Purchasing].[ShipMethod] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Vendor_AccountNumber] ON [Purchasing].[Vendor] ([AccountNumber] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_CountryRegionCurrency_CurrencyCode] ON [Sales].[CountryRegionCurrency] ([CurrencyCode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_CreditCard_CardNumber] ON [Sales].[CreditCard] ([CardNumber] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Currency_Name] ON [Sales].[Currency] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_CurrencyRate_CurrencyRateDate_FromCurrencyCode_ToCurrencyCode] ON [Sales].[CurrencyRate] ([CurrencyRateDate] ASC, [FromCurrencyCode] ASC, [ToCurrencyCode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Customer_AccountNumber] ON [Sales].[Customer] ([AccountNumber] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Customer_rowguid] ON [Sales].[Customer] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_Customer_TerritoryID] ON [Sales].[Customer] ([TerritoryID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesOrderDetail_rowguid] ON [Sales].[SalesOrderDetail] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_SalesOrderDetail_ProductID] ON [Sales].[SalesOrderDetail] ([ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesOrderHeader_rowguid] ON [Sales].[SalesOrderHeader] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesOrderHeader_SalesOrderNumber] ON [Sales].[SalesOrderHeader] ([SalesOrderNumber] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_SalesOrderHeader_CustomerID] ON [Sales].[SalesOrderHeader] ([CustomerID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_SalesOrderHeader_SalesPersonID] ON [Sales].[SalesOrderHeader] ([SalesPersonID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesPerson_rowguid] ON [Sales].[SalesPerson] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesPersonQuotaHistory_rowguid] ON [Sales].[SalesPersonQuotaHistory] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesTaxRate_rowguid] ON [Sales].[SalesTaxRate] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesTaxRate_StateProvinceID_TaxType] ON [Sales].[SalesTaxRate] ([StateProvinceID] ASC, [TaxType] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesTerritory_Name] ON [Sales].[SalesTerritory] ([Name] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesTerritory_rowguid] ON [Sales].[SalesTerritory] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SalesTerritoryHistory_rowguid] ON [Sales].[SalesTerritoryHistory] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_ShoppingCartItem_ShoppingCartID_ProductID] ON [Sales].[ShoppingCartItem] ([ShoppingCartID] ASC, [ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SpecialOffer_rowguid] ON [Sales].[SpecialOffer] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_SpecialOfferProduct_rowguid] ON [Sales].[SpecialOfferProduct] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_SpecialOfferProduct_ProductID] ON [Sales].[SpecialOfferProduct] ([ProductID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE NONCLUSTERED INDEX [AK_Store_rowguid] ON [Sales].[Store] ([rowguid] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE NONCLUSTERED INDEX [IX_Store_SalesPersonID] ON [Sales].[Store] ([SalesPersonID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE PRIMARY XML INDEX [PXML_Store_Demographics] ON [Sales].[Store] ([Demographics]) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100);

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE CLUSTERED INDEX [IX_vStateProvinceCountryRegion] ON [Person].[vStateProvinceCountryRegion] ([StateProvinceID] ASC, [CountryRegionCode] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

-- SQRIBE/OBJ;341e11
CREATE UNIQUE CLUSTERED INDEX [IX_vProductAndDescription] ON [Production].[vProductAndDescription] ([ProductID] ASC, [CultureID] ASC) WITH (PAD_INDEX=OFF, ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS=ON, STATISTICS_NORECOMPUTE=OFF, IGNORE_DUP_KEY=OFF, SORT_IN_TEMPDB=OFF, FILLFACTOR=100) ON [PRIMARY];

GO -- SQRIBE/GO;341e11

